#!/usr/bin/perl

use strict;

my @vm = `defaults read com.epages.st3plugin vm`;
chomp(@vm);
my $vmName = $vm[0];
# $vmName =~ s/\n//g;

exit 1 unless $ARGV[0];

print `cat $ARGV[0] | ssh root\@$vmName /srv/epages/eproot/Perl/bin/perl /srv/epages/eproot/tlec.pl`;
